### ISSUE TITLE
Can't subscribe and get the data from AIO Feeds

### ISSUE THREAD

**Issue by plekotho** [SensorsIot/MQTT-Examples#2]
i've follow all your steps, but it doesn't work for me to receive data from the server (callback data).
I've successfully connect to MQTT and want to subscribe to the feeds from AIO.
I don't get any error, but the data just not showing. It keeps trying and trying to subsribe / get the data.
I've check the AIO dashboard and know that the data is there.
What's wrong? I've tried to solve this issue using 
-https://github.com/adafruit/Adafruit_MQTT_Library/issues/31
-https://github.com/adafruit/Adafruit_MQTT_Library/issues/76

Nothing works. 
I'm using wemos D1 mini. IFTTT twitter post(trigger) to AIO.

pls help

**Comment by SensorsIot** [comment]
I just tested it with my PubSub library example (I mostly use this library) and it worked.
